### ISSUE TITLE
EXPLORATION: Adding Lombok to project

### ISSUE THREAD

**Issue by Adam1302** [Adam1302/SpringBoot-AML#17]
**What?**
See [Introduction to Project Lombok | Baeldung](https://www.baeldung.com/intro-to-project-lombok)
At the very least, we can add some annotations. Lombok seems to be omnipresent in SpringBoot projects

**Why?**
Lombok allows us to write cleaner code and avoid common coding tasks by generating byte code for us.

**How?**
Look through the catalog of annotations offered by Lombok. Which ones can reduce our code or add useful functionality?

**Comment by imvignesh003** [comment]
I'm interested in adding Lombok to this project. Can I please be assigned to this issue?

**Comment by Adam1302** [comment]
Sure @imvignesh003 , I have assigned it to you. Please feel free to explore the Baeldung link for ways to add Lombok features (some features are already added).

I can test for you if you can't set up locally.

Please reach out for any advice/questions

**Comment by imvignesh003** [comment]
I need help in setting it up locally @Adam1302

**Comment by Adam1302** [comment]
@imvignesh003 sure, have you followed the README.md instructions? Where are you stuck?

**Comment by imvignesh003** [comment]
I have created the db in the docker container and I don't know how to run the sql file in the postgres cmd.
And also i'm lagging behind in connecting the spring application with the postgres

![image](https://github.com/Adam1302/SpringBoot-AML/assets/111968851/f5c52823-e10d-4d46-986d-36103bdc0310)

**Comment by Adam1302** [comment]
@imvignesh003 Thank you for the info. I will take a look tonight and update the instructions.

**Comment by Adam1302** [comment]
@imvignesh003 for now, one idea that comes to mind is that you might need to update the password in src/main/resources/application.yml. Currently it is set to a generic "password"

**Comment by imvignesh003** [comment]
I see that the DTO and the model classes were already been simplified by lombok....Can I know if anything I can do?

**Comment by Adam1302** [comment]
@imvignesh003 you're right, apologies, this ticket must have been leftover. Feel free to pick up another ticket if you'd like. I will close this issue
