### ISSUE TITLE
FEATURE: Add @JsonProperty to DTO Fields

### ISSUE THREAD

**Issue by Adam1302** [Adam1302/SpringBoot-AML#21]
**What?**
Add @JsonProperty to DTO Fields after DTO creation

**Why?**
The coupling of JSON and model fields is unnecessary and makes us use snake_case. Let's change

**How?**
(see Spring Docs for instructions)

**Comment by kamaljitkaur98** [comment]
Hi Happy to take this up ! Please assign

**Comment by Adam1302** [comment]
Hi @kamaljitkaur98 . Awesome! However, this issue is blocked by #28 -- we have to add the DTOs first. Currently we just have everything stored in the Model. I will plan to complete DTO introduction by tomorrow. Please feel free to work on. #28 if you'd like. Please use https://www.youtube.com/watch?v=5yquJa2x3Ko for pattern/styling reference.

**Comment by Adam1302** [comment]
@kamaljitkaur98 
I have implemented DTOs, I will assign to you now if you'd like to implement it in the next couple days.
Please use https://www.baeldung.com/jackson-annotations#1-jsonproperty for reference. I would like to have our JSON properties in _snake_case_ and our DTO fields in camelCase. This ticket also includes the refactoring of any getters.

**Comment by kamaljitkaur98** [comment]
The Book model is in snake_case. Do we want to refractor those to camelCase too?

**Comment by Adam1302** [comment]
> The Book model is in snake_case. Do we want to refractor those to camelCase too?

Sure, good reminder @kamaljitkaur98
