### ISSUE TITLE
FEATURE: Add search-by endpoint to support search bar GET requests

### ISSUE THREAD

**Issue by Adam1302** [Adam1302/SpringBoot-AML#73]
The endpoint will be a GET request

It will request a parameter from the HTTP request that tells it what we're searching by (i.e. search by title, search by author). If no parameter is provided, it will search by both author and title and return the combined list of books. 

It will also accept a string (the text being searched) as another parameter

The ticket involves the service and DAO logic, as well.

Some resources to guide you on the ticket:
- Step 3 here: https://www.geeksforgeeks.org/spring-boot-build-a-dynamic-full-text-search-api-using-jpa-queries/

**Comment by developer-rohith** [comment]
I'm interested in working on this issue and would like to contribute a solution. Is there anything specific I should know before getting started? Looking forward to diving into this!

**Comment by Adam1302** [comment]
Hi @developer-rohith . That's great, I have assigned the issue to you.

This ticket involves adding the endpoint in the controller and adding the logic methods in the service and DAO. I imagine the service method should be pretty simple, and the DAO JDBCtemplate call should make an SQL call similar to the example in the GeeksForGeeks site.

If you have trouble setting up the project on your end (see README.md for instructions), I can also test your changes for you on my end. In any case, please add me as a reviewer on your pull request.

Please leave a comment here if you are stuck at all and I will respond within 24 hours.

**Comment by Adam1302** [comment]
Unassigning after inactivity
